### ISSUE TITLE
can not run the command 

### ISSUE THREAD

**Issue by AmalAldawsari** [febo/myra#6]
i tried this command " java -cp myra-5.0.jar myra.algorithm.ContinuousAntMiner -f breast.cencer.arff" in the same directory that has the dataset file and the jar file as well. 

The error i got was 
"Error: Could not find or load main class myra.algorithm.ContinuousAntMiner
Caused by: java.lang.ClassNotFoundException: myra.algorithm.ContinuousAntMiner"

could you please advice how to fix this issue?
Thanks

**Comment by rizauddin** [comment]
> i tried this command " java -cp myra-5.0.jar myra.algorithm.ContinuousAntMiner -f breast.cencer.arff" in the same directory that has the dataset file and the jar file as well.
> 
> The error i got was "Error: Could not find or load main class myra.algorithm.ContinuousAntMiner Caused by: java.lang.ClassNotFoundException: myra.algorithm.ContinuousAntMiner"
> 
> could you please advice how to fix this issue? Thanks

You need to run the command within the same directory with myra-5.0.jar.

**Comment by Djihanegh** [comment]
Use the Full path to your main class , for example  C:\Users\YourUsername\Documents\ML\myra\target\classes myra.algorithm.AntMiner

**Comment by febo** [comment]
@AmalAldawsari Can you double check the content of the directory that you are executing the command from? I cannot reproduce the error - the command that you are using should work fine if the `jar` file is in the same directory.
